export enum UserDITokens {
    USER_REPOSITORY = 'USER_REPOSITORY',
    USER_PROFILE_REPOSITORY = 'USER_PROFILE_REPOSITORY',
    USER_ROLE_REPOSITORY = 'USER_ROLE_REPOSITORY',
    ROLE_REPOSITORY = 'ROLE_REPOSITORY',
}
