export enum ConfigKeys {
    NODE_ENV = 'NODE_ENV',
    CLIENT_URL = 'CLIENT_URL',

    APP_HOST = 'APP_HOST',
    APP_PORT = 'APP_PORT',

    JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
    JWT_ACCESS_TOKEN_TTL_IN_MINUTES = 'JWT_ACCESS_TOKEN_TTL_IN_MINUTES',
    JWT_ACCESS_TOKEN_HEADER = 'JWT_ACCESS_TOKEN_HEADER',
    JWT_LOGIN_USERNAME_FIELD = 'JWT_LOGIN_USERNAME_FIELD',
    JWT_LOGIN_PASSWORD_FIELD = 'JWT_LOGIN_PASSWORD_FIELD',

    ENABLE_LOG = 'ENABLE_LOG',

    THROTTLER_LIMIT = 'THROTTLER_LIMIT',
    THROTTLER_TTL_IN_MINUTES = 'THROTTLER_TTL_IN_MINUTES',

    HEALTH_HTTP_URL = 'HEALTH_HTTP_URL',
    HEALTH_STORAGE_THRESHOLD_IN_PERCENT = 'HEALTH_STORAGE_THRESHOLD_IN_PERCENT',
    HEALTH_HEAP_MEMORY_THRESHOLD_IN_MB = 'HEALTH_HEAP_MEMORY_THRESHOLD_IN_MB',
    HEALTH_RSS_MEMORY_THRESHOLD_IN_MB = 'HEALTH_RSS_MEMORY_THRESHOLD_IN_MB',
    HEALTH_SHUTDOWN_TIMEOUT_IN_MS = 'HEALTH_SHUTDOWN_TIMEOUT_IN_MS',

    MAIL_HOST = 'MAIL_HOST',
    MAIL_PORT = 'MAIL_PORT',
    MAIL_USER = 'MAIL_USER',
    MAIL_PASS = 'MAIL_PASS',
    MAIL_FROM = 'MAIL_FROM',

    DB_HOST = 'DB_HOST',
    DB_PORT = 'DB_PORT',
    DB_USERNAME = 'DB_USERNAME',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_NAME = 'DB_NAME',
    DB_LOG_ENABLE = 'DB_LOG_ENABLE',

    REDIS_HOST = 'REDIS_HOST',
    REDIS_PORT = 'REDIS_PORT',
    REDIS_USERNAME = 'REDIS_USERNAME',
    REDIS_PASSWORD = 'REDIS_PASSWORD',

    CLOUDFLARE_ACCOUNT_ID = 'CLOUDFLARE_ACCOUNT_ID',
    CLOUDFLARE_API_TOKEN = 'CLOUDFLARE_API_TOKEN',

    R2_REGION = 'R2_REGION',
    R2_ACCESS_KEY_ID = 'R2_ACCESS_KEY_ID',
    R2_SECRET_ACCESS_KEY = 'R2_SECRET_ACCESS_KEY',
    R2_PROFILE_BUCKET_NAME = 'R2_PROFILE_BUCKET_NAME',
    R2_CONTENT_BUCKET_NAME = 'R2_CONTENT_BUCKET_NAME',
}
