export enum CoreDITokens {
    EVENT_BUS = 'EVENT_BUS',
    TASK_QUEUE = 'TASK_QUEUE',
    CACHE = 'CACHE',
    LOGGER = 'LOGGER',
    FILE_STORAGE = 'FILE_STORAGE',
    CONFIG = 'CONFIG',
    DB_TRANSACTION = 'DB_TRANSACTION',
    EVENT_SUBSCRIBER = 'EVENT_SUBSCRIBER',
}
